# Site settings
title: A Field Guide to Sam's Research
email: greydanus.17(at)gmail.com
description: "The natural science of cognition."
baseurl: ""
url: "http://greydanus.github.io"
twitter_username: samgreydanus
github_username: greydanus

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge